server:
  port: 8080

spring:
  application:
    name: Lbateau

  data:
    mongodb:
      auto-index-creation: true

  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  mongodb:
    uri: mongodb://127.0.0.1:27017/Lbateau

ai:
  service:
    url: http://localhost:5000

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG